# Generated by Django 3.2.7 on 2021-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('length', models.IntegerField(default=0)),
                ('average_g', models.IntegerField(default=0)),
            ],
        ),
    ]
