# Generated by Django 3.2.7 on 2021-10-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='average_g',
        ),
    ]
