# Generated by Django 3.2.7 on 2021-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_average_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.FloatField(default=0),
        ),
    ]
