# Generated by Django 3.2.7 on 2021-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_alter_track_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
