# Generated by Django 3.2.7 on 2021-10-28 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='track',
            name='available_to',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='track',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
