# Generated by Django 3.2.7 on 2021-10-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20211028_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='available_from',
            field=models.DateTimeField(max_length=128),
        ),
        migrations.AlterField(
            model_name='track',
            name='available_to',
            field=models.DateTimeField(max_length=128),
        ),
    ]
