# Generated by Django 3.2.7 on 2021-10-30 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20211028_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='track',
            name='available_to',
        ),
        migrations.AddField(
            model_name='track',
            name='date_available_from',
            field=models.DateField(default=datetime.datetime.now, max_length=128),
        ),
        migrations.AddField(
            model_name='track',
            name='date_available_until',
            field=models.DateField(default=datetime.datetime.now, max_length=128),
        ),
        migrations.AddField(
            model_name='track',
            name='time_available_from',
            field=models.TimeField(default=datetime.datetime.now, max_length=128),
        ),
        migrations.AddField(
            model_name='track',
            name='time_available_until',
            field=models.TimeField(default=datetime.datetime.now, max_length=128),
        ),
    ]
