# Generated by Django 3.2.7 on 2021-11-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_track_weather_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['id']},
        ),
    ]
