# Generated by Django 3.2.7 on 2021-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20211109_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='race_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
