# Generated by Django 3.2.7 on 2021-11-20 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_alter_track_race_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='race_day',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 20), null=True),
        ),
    ]
