# Generated by Django 3.2.7 on 2021-11-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0014_alter_track_race_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackAvailableDates',
        ),
    ]
