# Generated by Django 3.2.7 on 2021-10-15 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211015_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 8, 47, 26, 818725, tzinfo=utc)),
        ),
    ]
