# Generated by Django 3.2.7 on 2021-10-17 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211016_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 8, 39, 52, 109946, tzinfo=utc)),
        ),
    ]
