# Generated by Django 3.2.7 on 2021-10-26 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211021_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 9, 26, 51, 896476, tzinfo=utc)),
        ),
    ]
