# Generated by Django 3.2.7 on 2021-10-26 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_activation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 15, 50, 28, 332851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128, verbose_name='password'),
        ),
    ]
