# Generated by Django 3.2.7 on 2021-10-27 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20211027_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 10, 2, 19, 175454, tzinfo=utc)),
        ),
    ]
