# Generated by Django 3.2.7 on 2021-10-30 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20211028_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 0, 17, 833828, tzinfo=utc)),
        ),
    ]
