# Generated by Django 3.2.7 on 2021-11-01 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_activation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 24, 10, 310740, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
