# Generated by Django 3.2.7 on 2021-11-06 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20211105_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 9, 39, 30, 969015, tzinfo=utc)),
        ),
    ]
