# Generated by Django 3.2.7 on 2021-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_activation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='password'),
        ),
    ]
