# Generated by Django 3.2.7 on 2021-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_lap',
            field=models.IntegerField(default=1000),
        ),
    ]
