# Generated by Django 3.2.7 on 2021-10-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_delete_carimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_lap',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
