# Generated by Django 3.2.7 on 2021-11-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211027_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cars.car')),
            ],
        ),
    ]
