# Generated by Django 3.2.7 on 2021-11-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.category'),
        ),
    ]
