# Generated by Django 3.2.7 on 2021-11-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
