# Generated by Django 3.2.7 on 2021-10-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
