# Generated by Django 3.2.7 on 2021-10-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rate',
        ),
    ]
