# Generated by Django 3.2.7 on 2021-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20211030_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
