# Generated by Django 3.2.7 on 2021-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='booking',
            name='month',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='booking',
            name='year',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
