# Generated by Django 3.2.7 on 2021-11-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20211109_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='date_created',
        ),
    ]
