# Generated by Django 3.2.7 on 2021-11-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
