# Generated by Django 3.2.7 on 2021-11-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
