# Generated by Django 3.2.7 on 2021-11-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='month',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='year',
        ),
    ]
