# Generated by Django 3.2.7 on 2021-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20211120_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
